variables:
  NOX_VERSION: 2023.04.22

linux:
  image: python:3.8

  before_script:
    - pip install nox==$NOX_VERSION

  script:
    - nox --sessions tests --pythons 3.8 3.11

windows:
  tags:
    - shared-windows
    - windows
    - windows-1809

  before_script:
    - choco install python --version=3.8.10 -y -f
    - $Env:PATH += ";C:\Python38\Scripts"
    - pip install nox==$NOX_VERSION

  script:
    - nox --sessions tests --pythons 3.8
