linux:
  image: python:3.8

  before_script:
    - pip install nox

  script:
    - nox --sessions tests --pythons 3.8 3.11

windows:
  tags:
    - shared-windows
    - windows
    - windows-1809

  before_script:
    - choco install python --version=3.8.10 -y -f
    - C:\Python38\python.exe -m pip install nox
    - $Env:PATH += ";C:\Python38\Scripts"

  script:
    - nox --sessions tests --pythons 3.8
