variables:
  DEPS: nox==2024.10.09 poethepoet uv

linux:
  image: python:3.9

  before_script:
    - pip install $DEPS
    - uv sync

  script:
    - nox --sessions tests --pythons 3.9 3.11
    - poe zipapp

  artifacts:
    paths:
      - recur.pyz

windows:
  tags:
    - saas-windows-medium-amd64

  before_script:
    - choco install python --version=3.9.13 -y -f
    - $Env:PATH += ";C:\Python39\Scripts"
    - pip install ($DEPS -split " ")

  script:
    - nox --sessions tests --pythons 3.9
