variables:
  DEPS: nox==2023.04.22 nox-poetry==1.0.3 poethepoet poetry

linux:
  image: python:3.8

  before_script:
    - pip install $DEPS
    - poetry install

  script:
    - nox --sessions tests --pythons 3.8 3.11
    - poe zipapp

  artifacts:
    paths:
      - recur.pyz
windows:
  tags:
    - shared-windows
    - windows
    - windows-1809

  before_script:
    - choco install python --version=3.8.10 -y -f
    - $Env:PATH += ";C:\Python38\Scripts"
    - pip install ($DEPS -split " ")

  script:
    - nox --sessions tests --pythons 3.8
