version: '3'

vars:
  test_commands: |
    test/cat
    test/env
    test/exit99
    test/hello
    test/sleep

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  check:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-commands
      - build-readme

  build-commands:
    desc: 'Build all commands'
    deps:
      - build-recur
      - build-test-commands

  build-package:
    desc: 'Build a single Go package'
    internal: true
    dir: '{{.package}}'
    cmds:
      - go build -trimpath

  build-readme:
    desc: 'Update the usage section in "README.md" with current help'
    deps:
      - build-recur
    cmds:
      - go run ./script/readme
    status:
      - main.go
      - starlark.go
    generates:
      - README.md

  build-recur:
    desc: 'Build the recur command'
    cmds:
      - task: build-package
        vars:
          package: .
    sources:
      - main.go
      - starlark.go
    generates:
      - recur{{exeExt}}

  build-test-commands:
    desc: 'Build all test commands'
    cmds:
      - task: build-package
        vars:
          package: '{{.test_command}}'
        for:
          var: test_commands
          as: test_command
    sources:
      - test/**/*.go
    generates:
      - test/cat/cat{{exeExt}}
      - test/env/env{{exeExt}}
      - test/exit99/exit99{{exeExt}}
      - test/hello/hello{{exeExt}}
      - test/sleep/sleep{{exeExt}}

  clean:
    desc: 'Clean up binaries and generated files'
    cmds:
      - rm -f recur{{exeExt}}
      - cmd: rm -f {{.test_command | shellQuote}}{{.test_command | base | shellQuote}}{{exeExt}}
        for:
          var: test_commands
          as: test_command

  lint:
    desc: 'Run golangci-lint'
    cmds:
      - golangci-lint run

  release:
    desc: 'Prepare a release'
    deps:
      - build-commands
    cmds:
      - VERSION=$(./recur{{exeExt}} --version) go run ./script/release

  test:
    desc: 'Run tests'
    deps:
      - build-commands
    cmds:
      - go test
