version: '3'

vars:
  dist_dir: dist/
  ext: '{{if eq OS "windows"}}.exe{{end}}'
  test_binaries: |
    test/cat
    test/env
    test/exit99
    test/hello
    test/sleep

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-readme
      - build-binaries

  build-binaries:
    desc: 'Build all necessary binaries'
    deps:
      - build-recur
      - build-test-binaries

  build-binary:
    desc: 'Build a single Go binary'
    internal: true
    cmds:
      - go build -o {{.out | shellQuote}}{{.ext}}{{range (.srcs | trim | splitLines)}} {{. | shellQuote}}{{end}}

  build-readme:
    desc: 'Generate README.md from template'
    deps:
      - build-recur
    cmds:
      - go run script/render_template.go < README.template.md > README.md
    status:
      - README.template.md
      - main.go
      - starlark.go
    generates:
      - README.md

  build-recur:
    desc: 'Build the recur binary'
    cmds:
      - task: build-binary
        vars:
          out: recur
          srcs: |
            main.go
            starlark.go
    sources:
      - main.go
      - starlark.go
    generates:
      - recur{{.ext}}

  build-test-binaries:
    desc: 'Build all test binaries'
    cmds:
      - task: build-binary
        vars:
          out: '{{.test_binary}}'
          srcs: '{{.test_binary}}.go'
        for:
          var: test_binaries
          as: test_binary
    sources:
      - test/cat.go
      - test/env.go
      - test/exit99.go
      - test/hello.go
      - test/sleep.go
    generates:
      - test/cat{{.ext}}
      - test/env{{.ext}}
      - test/exit99{{.ext}}
      - test/hello{{.ext}}
      - test/sleep{{.ext}}

  clean:
    desc: 'Clean up binaries and generated files'
    cmds:
      - rm -f README.md
      - rm -f recur{{.ext}}
      - cmd: rm -f {{.test_binary | shellQuote}}{{.ext}}
        for:
          var: test_binaries
          as: test_binary

  release:
    desc: 'Prepare a release'
    deps:
      - build-binaries
    cmds:
      - VERSION=$(./recur{{.ext}} --version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build-binaries
    cmds:
      - go test
