version: '3'

vars:
  dist_dir: dist/
  test_binaries: |
    test/cat
    test/env
    test/exit99
    test/hello
    test/sleep

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  check:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-readme
      - build-binaries

  build-binaries:
    desc: 'Build all necessary binaries'
    deps:
      - build-recur
      - build-test-binaries

  build-binary:
    desc: 'Build a single Go binary'
    internal: true
    cmds:
      - go build -o {{.out | shellQuote}}{{exeExt}}{{range (.srcs | trim | splitLines)}} {{. | shellQuote}}{{end}}

  build-readme:
    desc: 'Update the usage section in "README.md" with current help'
    deps:
      - build-recur
    cmds:
      - go run script/update_readme.go
    status:
      - README.md
      - main.go
      - starlark.go
    generates:
      - README.md

  build-recur:
    desc: 'Build the recur binary'
    cmds:
      - task: build-binary
        vars:
          out: recur
          srcs: |
            main.go
            starlark.go
    sources:
      - main.go
      - starlark.go
    generates:
      - recur{{exeExt}}

  build-test-binaries:
    desc: 'Build all test binaries'
    cmds:
      - task: build-binary
        vars:
          out: '{{.test_binary}}'
          srcs: '{{.test_binary}}.go'
        for:
          var: test_binaries
          as: test_binary
    sources:
      - test/cat.go
      - test/env.go
      - test/exit99.go
      - test/hello.go
      - test/sleep.go
    generates:
      - test/cat{{exeExt}}
      - test/env{{exeExt}}
      - test/exit99{{exeExt}}
      - test/hello{{exeExt}}
      - test/sleep{{exeExt}}

  clean:
    desc: 'Clean up binaries and generated files'
    cmds:
      - rm -f recur{{exeExt}}
      - cmd: rm -f {{.test_binary | shellQuote}}{{exeExt}}
        for:
          var: test_binaries
          as: test_binary

  lint:
    desc: 'Run golangci-lint'
    cmds:
      - golangci-lint run

  release:
    desc: 'Prepare a release'
    deps:
      - build-binaries
    cmds:
      - VERSION=$(./recur{{exeExt}} --version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build-binaries
    cmds:
      - go test
