version: '3'

vars:
  TEST_HELPERS: |
    test/cat
    test/env
    test/exit99
    test/hello
    test/sleep

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  check:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  build:
    desc: 'Build all components'
    deps:
      - build:bin
      - build:readme

  build:bin:
    desc: 'Build all binaries'
    deps:
      - build:recur
      - build:helpers

  build:package:
    desc: 'Build a single Go package'
    internal: true
    dir: '{{.PACKAGE}}'
    cmds:
      - 'go build -trimpath # {{.PACKAGE}}'

  build:readme:
    desc: 'Update the usage section in "README.md" with current help'
    run: once
    deps:
      - build:recur
    cmds:
      - go run ./script/readme ./recur --help
    sources:
      - main.go
      - script/readme/main.go
    generates:
      - README.md

  build:recur:
    desc: 'Build the recur binary'
    run: once
    cmds:
      - task: build:package
        vars:
          PACKAGE: .
    sources:
      - main.go
      - starlark.go
    generates:
      - recur{{exeExt}}

  build:helpers:
    desc: 'Build all test helpers'
    run: once
    cmds:
      - task: build:package
        vars:
          PACKAGE: '{{.HELPER}}'
        for:
          var: TEST_HELPERS
          as: HELPER
    sources:
      - test/**/*.go
    status:
      - '{{range $i, $path := .TEST_HELPERS | trim | splitLines}}{{if $i}} && {{end}}test -f {{$path | shellQuote}}/{{$path | base | shellQuote}}{{exeExt}}{{end}}'

  clean:
    desc: 'Clean up binaries and generated files'
    cmds:
      - rm -f recur{{exeExt}}
      - cmd: rm -f {{.HELPER | shellQuote}}/{{.HELPER | base | shellQuote}}{{exeExt}}
        for:
          var: TEST_HELPERS
          as: HELPER

  lint:
    desc: 'Run golangci-lint'
    cmds:
      - golangci-lint run

  release:
    desc: 'Prepare a release'
    deps:
      - build:bin
    cmds:
      - VERSION=$(./recur{{exeExt}} --version) go run ./script/release

  test:
    desc: 'Run tests'
    deps:
      - build:bin
    cmds:
      - go test
